### PR TITLE
Update requirements

### PR DESCRIPTION
**Pull request by antonio-ramadas**
Hey!

While I was checking out the project, in order to make it run, I had to make some small changes. With these, I was able to obtain the same results as presented in the README file.

As this was helpful to me, I opened this PR because I believe it can help others.

Cheers,

### CODE REVIEW

**Comment by krasch** [comment]
Thanks! I'll look at it within the next days

**Comment by krasch** [comment]
I tried out the updated requirements and ran into the following issues

1. Could not install matplotlib
Probably makes sense to use a newer version for matplotlib, too. For now, I simply uncommented all the plotting, as to not mess with the versions of the other libraries.

2. Could not recreate the example results
The first table with precision / recall / F1 contains loads of NaNs  instead of the actual results. I suspect interface changes in one of the libraries. I am also seeing the following warnings:

```
/home/kat/.anaconda/envs/assistants2/lib/python2.7/site-packages/scipy/sparse/coo.py:182: VisibleDeprecationWarning: `rank` is deprecated; use the `ndim` attribute or function instead. To find the rank of a matrix see `numpy.linalg.matrix_rank`.
  if np.rank(M) != 2:
/home/kat/.anaconda/envs/assistants2/lib/python2.7/site-packages/scipy/sparse/coo.py:200: VisibleDeprecationWarning: `rank` is deprecated; use the `ndim` attribute or function instead. To find the rank of a matrix see `numpy.linalg.matrix_rank`.
  if np.rank(self.data) != 1 or np.rank(self.row) != 1 or np.rank(self.col) != 1:
/home/kat/.anaconda/envs/assistants2/lib/python2.7/site-packages/scipy/sparse/sputils.py:141: VisibleDeprecationWarning: `rank` is deprecated; use the `ndim` attribute or function instead. To find the rank of a matrix see `numpy.linalg.matrix_rank`.
  if np.rank(M) == 0 and np.rank(N) == 0:
/home/kat/.anaconda/envs/assistants2/lib/python2.7/site-packages/scipy/sparse/compressed.py:130: VisibleDeprecationWarning: `rank` is deprecated; use the `ndim` attribute or function instead. To find the rank of a matrix see `numpy.linalg.matrix_rank`.
  if np.rank(self.data) != 1 or np.rank(self.indices) != 1 or np.rank(self.indptr) != 1:
/home/kat/.anaconda/envs/assistants2/lib/python2.7/site-packages/numpy/core/_methods.py:135: RuntimeWarning: Degrees of freedom <= 0 for slice
  keepdims=keepdims)
/home/kat/.anaconda/envs/assistants2/lib/python2.7/site-packages/numpy/core/_methods.py:127: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
```
Are you also seing these? Did you ever see the NaN in the results table?

**Comment by antonio-ramadas** [comment]
> 1. Could not install matplotlib
> Probably makes sense to use a newer version for matplotlib, too. For now, I simply uncommented all the plotting, as to not mess with the versions of the other libraries.

I didn't test matplotlib, because I didn't change its version (or its code) and I assumed it was working.

> 2. Could not recreate the example results
>The first table with precision / recall / F1 contains loads of NaNs instead of the actual results. I suspect interface changes in one of the libraries. I am also seeing the following warnings:

About the NaNs, you are probably right. At the time I noticed the NaNs in the results table, but I've to confess I didn't pay much attention to them at the time (my goal was to study the implementation details).

I'm not sure if updating the requirements to another previous version would fix these problems. Currently, I don't have enough time to spend on this issue, but I'll try to address it in the future. In any case, help is welcome.

**Comment by rebeen** [comment]
I only want to run smart-assistants/datasets/converters/kasteren.py but it has many errors and it is strange that shows some variables are not defined!

**Comment by rebeen** [comment]
I have used your source code to export the CSV file and I realized that we only have 8 activities in both datasets A and B while the original paper of this datasets shows that the A has 10, B has 13 and C has 16 activities, please do you have any idea why we get fewer activities when we export the CSV files?

Thank you

**Comment by antonio-ramadas** [comment]
> do you have any idea why we get fewer activities when we export the CSV files?

I haven't looked at this in a while. I can only guess.

**Comment by krasch** [comment]
@rebeen It seems your issue has nothing to do with this pull request. Could you please create a separate issue with some info on the steps you have run so far and python version used?

**Pull request closed without merging**
